export const blogPosts = [
  {
    slug: "tipos-envases-pet-industria-alimenticia",
    title: "Tipos de envases PET para la industria alimenticia en México",
    description:
      "Guía completa sobre los diferentes tipos de envases PET utilizados en la industria alimenticia mexicana: botellas, frascos, tapas y más. Conoce sus características, ventajas y aplicaciones.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Proveedor de envases PET en México",
    category: "Envases PET",
    tags: [
      "envases PET",
      "industria alimenticia",
      "botellas PET",
      "frascos PET",
      "packaging",
    ],
    readingTime: "7 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "¿Por qué el PET es el material líder en envases para alimentos?",
      "Tipos de envases PET para la industria alimenticia",
      "Cómo elegir el envase PET adecuado para tu producto",
      "Tendencias actuales en envases PET para alimentos en México",
    ],
  },
  {
    slug: "como-elegir-proveedor-envases-pet",
    title: "¿Cómo elegir al mejor proveedor de envases PET en México?",
    description:
      "Aprende a evaluar proveedores de envases PET para tu negocio. Calidad, precios, ubicación, servicio y más factores clave para tomar la mejor decisión en la industria del packaging.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Proveedor líder de envases PET",
    category: "Proveedores",
    tags: [
      "proveedor de envases PET",
      "packaging",
      "proveedor packaging",
      "envases México",
    ],
    readingTime: "6 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "Factores clave para elegir un proveedor de envases PET",
      "Banderas rojas al elegir proveedor de envases PET",
      "Por qué elegir a Envases La Merced como tu proveedor de envases PET",
    ],
  },
  {
    slug: "envases-pet-vs-otros-materiales",
    title: "Envases PET vs otros materiales: ¿cuál elegir para tu producto?",
    description:
      "Comparativa detallada entre envases PET, vidrio, HDPE, PP y aluminio. Descubre las ventajas de cada material y cuándo el PET es la mejor opción para tu negocio.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Especialistas en envases PET",
    category: "Envases PET",
    tags: [
      "envases PET",
      "PET vs vidrio",
      "materiales de envasado",
      "empaques plásticos",
      "packaging industrial",
    ],
    readingTime: "8 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "PET vs Vidrio: ligereza y resistencia",
      "PET vs HDPE: transparencia y rigidez",
      "PET vs PP: claridad y barrera",
      "PET vs Aluminio: versatilidad y costo",
      "¿Cuándo elegir envases PET?",
    ],
  },
  {
    slug: "envases-pet-para-cosmeticos",
    title: "Guía de envases PET para productos cosméticos y cuidado personal",
    description:
      "Todo lo que necesitas saber sobre envases PET para cosméticos: cremas, lociones, shampoos, geles y más. Formatos, acabados premium y compatibilidad química.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Proveedor de envases para cosméticos",
    category: "Envases PET",
    tags: [
      "envases PET cosméticos",
      "frascos para cremas",
      "envases shampoo",
      "packaging cosmético",
      "botellas PET cosmética",
    ],
    readingTime: "7 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "¿Por qué el PET es ideal para cosméticos?",
      "Tipos de envases PET para cosméticos",
      "Acabados premium para destacar en anaquel",
      "Compatibilidad química y seguridad",
      "Tendencias en packaging cosmético",
    ],
  },
  {
    slug: "sustentabilidad-reciclaje-pet-mexico",
    title:
      "Sustentabilidad en envases PET: reciclaje y economía circular en México",
    description:
      "El PET es 100% reciclable y México es líder mundial en reciclaje de este material. Conoce la cadena de reciclaje, el rPET y cómo tu empresa puede sumarse a la economía circular.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Comprometidos con la sustentabilidad",
    category: "Sustentabilidad",
    tags: [
      "reciclaje PET México",
      "rPET",
      "economía circular",
      "envases sustentables",
      "packaging ecológico",
    ],
    readingTime: "7 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "El PET y el mito del plástico contaminante",
      "Cadena de reciclaje de PET en México",
      "PET reciclado (rPET): qué es y cómo se utiliza",
      "Beneficios económicos y ambientales del rPET",
      "Cómo tu empresa puede contribuir al reciclaje",
    ],
  },
  {
    slug: "normatividad-envases-pet-mexico",
    title:
      "Normatividad y certificaciones para envases PET en la industria mexicana",
    description:
      "Guía práctica sobre las normas y certificaciones que deben cumplir los envases PET en México: COFEPRIS, NOM, FDA y estándares de calidad. Cumplimiento para alimentos, cosméticos y más.",
    date: "2026-07-04",
    author: "Envases La Merced",
    authorRole: "Expertos en normatividad de envases",
    category: "Normatividad",
    tags: [
      "normatividad envases PET",
      "COFEPRIS envases",
      "NOM envases plásticos",
      "certificación FDA",
      "regulaciones packaging México",
    ],
    readingTime: "8 min",
    image: "/assets/bg_img/bg2.webp",
    toc: [
      "COFEPRIS y los envases para alimentos y bebidas",
      "NOM-251-SSA1-2009: prácticas de higiene para envases",
      "NOM-086-SSA1: etiquetado de alimentos y bebidas",
      "Certificación FDA para productos de exportación",
      "Estándares de calidad en la fabricación de envases PET",
      "Cómo verificar que tu proveedor cumple con la normatividad",
    ],
  },
];
